services:
    notification.email:
        class: NotificationBundle\Service\EmailService
        arguments:
            - "@swiftmailer.mailer.abstract"
            - "@templating.engine.twig"
            - Html2Text\Html2Text
            - "%notification%"
