services:
    notification.email:
        class: NotificationBundle\Service\EmailService
        arguments:
            - "@swiftmailer.mailer"
            - "@templating.engine.twig"
            - "%notification%"
